config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  get '/products', :to => 'products#index'
  mount ShopifyApp::Engine, at: '/'
  devise_for :users
  # root to: 'pages#home'

  resources :ab_tests do
    resources :segments, only: [:new, :create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'ab_test_data', to: 'ab_tests#ab_test_data'
      get 'js_lib', to: 'ab_tests#js_lib'
    end
  end
end

app/models/ab_test.rb
class AbTest < ApplicationRecord
  belongs_to :shop
  has_many :segments
  has_secure_token
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/segment.rb
class Segment < ApplicationRecord
  belongs_to :ab_test

  has_secure_token :ab_token

  validates :name, presence: true
end

app/models/shop.rb
# frozen_string_literal: true
class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorage

  has_many :ab_tests

  def api_version
    ShopifyApp.configuration.api_version
  end

  def with_shopify!
    # TODO: If you want to work with another shop, you'll first need to clear the session:
    ShopifyAPI::Base.clear_session
    session = ShopifyAPI::Session.new(domain: shopify_domain, token: shopify_token, api_version: api_version)
    ShopifyAPI::Base.activate_session(session)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/ab_tests_controller.rb
class AbTestsController < AuthenticatedController
  before_action :set_ab_test, only: [:show, :edit, :update]
  before_action :verbose_shopify

  def index
    @ab_tests = current_shop.ab_tests
  end

  def show
  end

  def new
    @ab_test = AbTest.new
  end

  def create
    @ab_test = AbTest.new(ab_test_params)
    @ab_test.shop = current_shop
    if @ab_test.save
      redirect_to ab_test_path(@ab_test)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ab_test.update(ab_test_params)
      redirect_to ab_test_path(@ab_test)
    else
      render :edit
    end
  end


  private

  def set_ab_test
    @ab_test = current_shop.ab_tests.find(params[:id])
  end

  def ab_test_params
    params.require(:ab_test).permit(:name, :active)
  end

  def verbose_shopify
    puts "Verbose"
    p current_shop
    p current_shopify_domain
  end
end

app/controllers/api/v1/ab_tests_controller.rb
class Api::V1::AbTestsController < Api::V1::BaseController
  # protect_from_forgery, except: :ab_test_data
  def ab_test_data
    @ab_test = AbTest.find_by(token: params[:token])

    segment = @ab_test.segments.sample
    segment.total_views += 1
    segment.save

    render json: { segment_url: segment.url }
  end

  def js_lib
    render file: '/api/v1/ab_tests/js_lib', handlers: [:erb], formats: [:js], locals: { name: "John" }, layout: false
    # format.js do
    #   render "segment_rendering", layout: false
    # end
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  rescue_from StandardError, with: :error_response

  before_action :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

  private

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def error_response(exception)
    render json: { error: exception.message }, status: 500
  end
end

app/controllers/api/v1/segments_controller.rb
class Api::V1::SegmentsController < Api::V1::BaseController
  def segment_url

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated

  def current_shop
    ShopifyAPI::Shop.current
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop

  def index
    @shop_origin = current_shopify_domain
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    render(json: { products: @products })
  end
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_ab_test, only: [:new, :create]

  def new
    @segment = Segment.new
  end

  def create
    @segment = Segment.new(segment_params)
    @segment.ab_test = @ab_test
    if @segment.save
      redirect_to ab_test_path(@ab_test)
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  private
  def set_ab_test
    @ab_test = AbTest.find(params[:ab_test_id])
  end

  def segment_params
    params.require(:segment).permit(:name, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ab_tests/_form.html.erb
<%= simple_form_for @ab_test do |f| %>
  <%= f.input :name %>
  <%= f.input :active %>
  <%= f.submit %>
<% end %>

app/views/ab_tests/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="white-card">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/ab_tests/index.html.erb
<div class="container">
  <div class="row">
    <% @ab_tests.each do |ab_test| %>
      <div class="col-3">
        <div class="white-card">
          <h1><%= ab_test.name %> </h1>

          <div class="test-links">
            <%= link_to ab_test_path(ab_test) do %>
              <i class="fas fa-eye"></i>
            <% end %>
            <%= link_to edit_ab_test_path(ab_test) do %>
              <i class="fas fa-edit"></i>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/ab_tests/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="white-card">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/ab_tests/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="white-card">
        <h1><%= @ab_test.name %> </h1>
        <p><%= @ab_test.active ? "ACTIVE" : "INACTIVE" %></p>

        <div class="segments">
          <ul>
            <% @ab_test.segments.each do |segment| %>
              <li><%= segment.name %> - <%= segment.url %> </li>
            <% end %>
          </ul>
        </div>

        <%= link_to "Add Segment", new_ab_test_segment_path(@ab_test), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://unpkg.com/@shopify/polaris@4.25.0/styles.min.css"
      />
    <script>
      document.addEventListener("DOMContentLoaded", async function() {
        var SessionToken = window["app-bridge"].actions.SessionToken
        var app = window.app;

        app.dispatch(
          SessionToken.request(),
        );

        // Save a session token for future requests
        window.sessionToken = await new Promise((resolve) => {
          app.subscribe(SessionToken.ActionType.RESPOND, (data) => {
            resolve(data.sessionToken || "");
          });
        });

        var fetchProducts = function() {
          var headers = new Headers({ "Authorization": "Bearer " + window.sessionToken });
          return fetch("/products", { headers })
            .then(response => response.json())
            .then(data => {
              var products = data.products;

              if (products === undefined || products.length == 0) {
                document.getElementById("products").innerHTML = "<br>No products to display.";
              } else {
                var list = "";
                products.forEach((product) => {
                  var link = `<a target="_top" href="https://<%= @shop_origin %>/admin/products/${product.id}">`
                  list += "<li>" + link + product.title + "</a></li>";
                });
                document.getElementById("products").innerHTML = "<ul>" + list + "</ul>";
              }
            });
        }();
      });
    </script>
  </head>
  <body>
    <%= link_to "View AB TESTS", ab_tests_path %>
    <div id="products"><br>Loading...</div>
    <h2>Webhooks</h2>

    <% if @webhooks.present? %>
    <ul>
      <% @webhooks.each do |webhook| %>
      <li><%= webhook.topic %> : <%= webhook.address %></li>
      <% end %>
    </ul>
    <% else %>
    <p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks</p>
    <% end %>
  </body>
</html>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AbMtk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://unpkg.com/@shopify/app-bridge"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: @shop_origin || (@current_shopify_session.domain if @current_shopify_session),
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<%= link_to "Create new AB Test", new_ab_test_path %>

app/views/segments/_form.html.erb
<%= simple_form_for [@ab_test, @segment] do |f| %>
  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.submit %>
<% end %>

app/views/segments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="white-card">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/segments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="white-card">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo.jpeg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Ab Tests", ab_tests_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>